#+title: Pudley todos

* TODO Fix script/01 naming scheme
- 02 has a proper naming helper
* TODO Unsatisfied with naming scheme and parameter saving in general...
- Think about
* TODO unsatisfied with my scripts lack of prose
- Think about that
- Org is not runnable (right now) and I want to develop on a script but be able to read my explanation later
- With that in mind there is a pkg for that, from scripts to notebooks. The notebooks should be generated on the appropriate folder!!!!
* TODO properly curry quickprobing
* TODO  the saving scheme in scripts/02-designplots is wrong
* TODO  add conversations to notes
* TODO [#A] Implement the following for andre
- Primeira coisa, não plote até estourar. Pare antes para a gente ver o comportamento inicial. Se estiver convergindo normalmente depois explode, é muito provável que seja precisão. Afinal o sigma está mesmo indo a zero. Para isso, esqueça a explosão final e vamos olhar o começo, só. E com zoom suficiente para a gente ver mais que só uma explosão.
