#+title: Pudley todos

* TODO Fix script/01 naming scheme
- 02 has a proper naming helper
* TODO Unsatisfied with naming scheme and parameter saving in general...
- Think about
* DONE unsatisfied with my scripts lack of prose
- Think about that
- Org is not runnable (right now) and I want to develop on a script but be able to read my explanation later
- With that in mind there is a pkg for that, from scripts to notebooks. The notebooks should be generated on the appropriate folder!!!!
* DONE properly curry quickprobing
* TODO  the saving scheme in scripts/02-designplots is wrong
* DONE add conversations to notes
* TODO [#A] Implement the following for andre
- Primeira coisa, não plote até estourar. Pare antes para a gente ver o
  comportamento inicial. Se estiver convergindo normalmente depois explode, é
  muito provável que seja precisão. Afinal o sigma está mesmo indo a zero. Para
  isso, esqueça a explosão final e vamos olhar o começo, só. E com zoom
  suficiente para a gente ver mais que só uma explosão.
- Eu acho que já disse antes, mas o que queremos ver é o comportamento antes de
  explodir. Pode rodar menos mesmo. E, se começar com um p ainda menor, deve
  demorar mais para dar problemas e a gente pode ver o comportamento antes da
  explosão. Vale verificar o que acontece, se a explosão some quando melhoramos
  a precisão, por exemplo, para ver se é isso mesmo. Sendo, nem há interesse
  naquela região. É só parar antes de dar problema e ver como as partículas
  probe se comportam em função da distância. Deveria dar que até uma certa
  distância se aproximam, depois se afastam.
